# CSR OMP KERNEL VERSIONS

set(SCPA_CSR_OMP_KERNEL_VERSIONS "")

set(SCPA_OMP_CSR_DIR "${CMAKE_CURRENT_SOURCE_DIR}/src/parallel/omp/csr")
file(GLOB SCPA_CSR_OMP_KERNELS ${SCPA_OMP_CSR_DIR}/*_v*.c)
foreach(SCPA_CSR_OMP_KERNEL_SOURCE ${SCPA_CSR_OMP_KERNELS})

    string(REGEX MATCH "^.*_v(([0-9]+\.)*[0-9]+)\.c$" _ ${SCPA_CSR_OMP_KERNEL_SOURCE})
    string(APPEND SCPA_CSR_OMP_KERNEL_VERSIONS "${CMAKE_MATCH_1};")

endforeach(SCPA_CSR_OMP_KERNEL_SOURCE ${SCPA_CSR_OMP_KERNELS})